#################################################################################
# Django Form for Test database model
#
# File: apps.py
# Name: James Aiken
# Date: 25/03/2019
# Course: CSC4006 - Research and Development Project
# Desc: File specifying the Django apps used in the TestingTool
#
# *Auto generated by Django skeleton*
#################################################################################

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.apps import AppConfig


class TestmanagerConfig(AppConfig):
    name = 'testmanager'
